import { TopBar } from "@/components/TopBar";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mt-7">
      <h2 className="font-display text-[17px] font-bold text-ink">{title}</h2>
      <div className="mt-2 space-y-2 text-[14.5px] leading-relaxed text-ink/70">{children}</div>
    </div>
  );
}

export default function AboutThisBuildPage() {
  return (
    <main className="min-h-dvh">
      <TopBar back={{ href: "/", label: "Home" }} />
      <section className="mx-auto w-full max-w-lg px-4 sm:max-w-xl sm:rounded-3xl sm:border sm:border-line sm:bg-card sm:px-10 sm:shadow-card sm:my-10 lg:max-w-2xl py-6 pb-16">
        <h1 className="font-display text-[24px] font-bold text-ink">What&rsquo;s real, what&rsquo;s mocked</h1>
        <p className="mt-2 text-[14.5px] text-ink/60">
          Sahaj is an independent hackathon prototype for &ldquo;Build What Moves India.&rdquo; It is not
          affiliated with the Government of India, MoRTH, Parivahan Sewa, or any RTO. No real government
          system is contacted at any point.
        </p>

        <Section title="Real in this build">
          <ul className="list-disc space-y-1.5 pl-4">
            <li>The full citizen journey works end-to-end: login → eligibility → details → documents → payment → slot → status tracking.</li>
            <li>The document pre-check and the Application Advocate call an actual OpenAI model (GPT-4o-mini) server-side when an API key is configured.</li>
            <li>Client and server validation is real — required fields, age checks, and document requirements are enforced, not decorative.</li>
            <li>The payment ledger, reference numbers, and refund messaging are generated by real application logic, not hardcoded text.</li>
          </ul>
        </Section>

        <Section title="Mocked, and clearly labelled in the UI">
          <ul className="list-disc space-y-1.5 pl-4">
            <li>Login is by mobile number and an on-screen OTP — no real SMS, Aadhaar, or DigiLocker integration.</li>
            <li>Payment is simulated. No real UPI, card, or bank is contacted; the three outcomes shown (success, delayed, debited-but-unmatched) mirror what citizens reported on the live portal.</li>
            <li>RTO slot availability and review timing are illustrative, not pulled from a real RTO calendar.</li>
            <li>All applicant data is fictional and stored only in your browser (localStorage) — nothing is sent to a shared database.</li>
            <li>When no OpenAI API key is configured, AI checks fall back to a deterministic simulated response, clearly marked <span className="font-mono text-[13px]">Demo mode</span> in the UI, so the journey never breaks.</li>
          </ul>
        </Section>

        <Section title="Architecture">
          <p>
            Next.js 16 (App Router, TypeScript) with server API routes standing in for backend services,
            deployed as a single Vercel project. State is client-owned (Zustand + localStorage) rather than
            a server database: Vercel&rsquo;s serverless functions are stateless between invocations, and
            adding a hosted database was judged unnecessary complexity for a prototype whose job is to prove
            the interaction model, not to run production infrastructure.
          </p>
          <p>
            The two AI routes are written so the citizen journey works identically whether or not an API
            key is present — a production system should never have a UI path that only works when a
            third-party API is reachable.
          </p>
        </Section>

        <Section title="How this could work safely at real scale">
          <ul className="list-disc space-y-1.5 pl-4">
            <li>Application state would move from the browser to a real database (e.g. Postgres) keyed by a verified Aadhaar/DigiLocker identity, with the client holding only a session token.</li>
            <li>Payment reconciliation would consume the bank/UPI switch&rsquo;s actual webhook events rather than a client-chosen outcome, with the same &ldquo;always show a status, always resolve or refund&rdquo; guarantee kept as a hard requirement, not a nicety.</li>
            <li>The document check and Application Advocate would need human-review fallback and audit logging before touching real applications — an LLM should narrow down what a human reviewer looks at, not make the final accept/reject call alone.</li>
            <li>Rate limiting, WAF, and a queueing layer in front of slot booking would replace the client-side 10-minute-hold placeholder shown here.</li>
          </ul>
        </Section>

        <Section title="Built with">
          <p>
            Next.js 16, TypeScript, Tailwind CSS, Zustand, and the OpenAI API (GPT-4o-mini). See the
            submission notes for how Codex was used in building and refining this prototype.
          </p>
        </Section>
      </section>
    </main>
  );
}
